export const KNOWLEDGE_STEPS = [
  {
    date: "Septiembre 2022 - Mayo 2024",
    title: "Ciclo Formativo de Grado Superior en Desarrollo de Aplicaciones Web",
    description:
      "Formación especializada en el diseño, desarrollo y mantenimiento de aplicaciones web. Este ciclo formativo me ha proporcionado habilidades avanzadas en lenguajes de programación, bases de datos, desarrollo frontend y backend, así como en metodologías ágiles. Durante este periodo, he trabajado en proyectos que incluyen la creación de interfaces de usuario intuitivas, la implementación de funcionalidades dinámicas y la optimización del rendimiento de aplicaciones web.",
    imageUrl: "/KnowledgeAssets/Logos/logo_irc.webp",
    hideTimeline: false,
    isHeadItem: true,
  },
  {
    date: "Septiembre 2020 - Junio 2022",
    title: "Bachillerato Tecnológico",
    description:
      "Estudios de bachillerato con especialización en Tecnología Industrial, Física y Dibujo Técnico. Durante este periodo, adquirí conocimientos sólidos en principios de ingeniería, análisis físico y representación gráfica, preparándome para estudios superiores en áreas tecnológicas y de desarrollo de aplicaciones.",
    imageUrl: "/KnowledgeAssets/Logos/logo_ilm.webp",
  },
];

export const items: CertDefinition[] = [
  {
    title: "Curso de PowerShell para principiantes",
    description: "A beginner's course on PowerShell.",
    logo: "/KnowledgeAssets/Logos/bLogos/openwebinars.webp",
    url: "test",
    issuedDate: new Date("2024-01-01"),
    issuedOrganization: "OpenWebinars",
  },
  {
    title: "Test de Aptitud de MongoDB",
    description: "Aptitude test for MongoDB skills.",
    logo: "/KnowledgeAssets/Logos/bLogos/openwebinars.webp",
    url: "test",
    issuedDate: new Date("2024-01-01"),
    issuedOrganization: "OpenWebinars",
  },
  {
    title: "Curso de Confluence: Funcionalidades y gestión documental",
    description: "Course on Confluence features and document management.",
    logo: "/KnowledgeAssets/Logos/bLogos/openwebinars.webp",
    url: "test",
    issuedDate: new Date("2023-11-01"),
    issuedOrganization: "OpenWebinars",
  },
  {
    title: "Petardos - Dependiente/a de tienda",
    description: "Curso sobre las habilidades necesarias para ser dependiente/a de tienda.",
    logo: "/KnowledgeAssets/Logos/bLogos/sepra.webp",
    url: "test",
    issuedDate: new Date("2023-05-01"),
    issuedOrganization: "SePra, SCC",
  },
  {
    title: "Manipulación manual de cargas",
    description: "Curso sobre la manipulación segura de cargas manuales.",
    logo: "/KnowledgeAssets/Logos/bLogos/quiroprevencion.webp",
    url: "test",
    issuedDate: new Date("2023-04-01"),
    issuedOrganization: "Quirónprevención",
  },
  {
    title: "Prevención de riesgos en puestos de industria cárnica",
    description: "Curso sobre la prevención de riesgos en la industria cárnica.",
    logo: "/KnowledgeAssets/Logos/bLogos/quiroprevencion.webp",
    url: "test",
    issuedDate: new Date("2023-04-01"),
    issuedOrganization: "Quirónprevención",
  },
  {
    title: "Seguridad en el manejo de transpaletas y apiladores",
    description: "Curso sobre seguridad en el manejo de transpaletas y apiladores.",
    logo: "/KnowledgeAssets/Logos/bLogos/quiroprevencion.webp",
    url: "test",
    issuedDate: new Date("2023-04-01"),
    issuedOrganization: "Quirónprevención",
  },
  {
    title: "Curso de Introducción al Desarrollo Web: HTML y CSS (2/2)",
    description: "Curso introductorio sobre el desarrollo web con HTML y CSS.",
    logo: "/KnowledgeAssets/Logos/bLogos/ualacant.webp",
    url: "test",
    issuedDate: new Date("2023-02-01"),
    issuedOrganization: "Universitat d'Alacant",
  },
  {
    title: "Curso de Introducción al Desarrollo Web: HTML y CSS (1/2)",
    description: "Curso introductorio sobre el desarrollo web con HTML y CSS.",
    logo: "/KnowledgeAssets/Logos/bLogos/ualacant.webp",
    url: "test",
    issuedDate: new Date("2023-01-01"),
    issuedOrganization: "Universitat d'Alacant",
  },
  {
    title: "Cloud Computing",
    description: "Curso sobre computación en la nube.",
    logo: "/KnowledgeAssets/Logos/bLogos/redes.webp",
    url: "test",
    issuedDate: new Date("2022-10-01"),
    issuedOrganization: "Red.es",
  },
  {
    title: "Digitaliza paso a paso tu negocio con herramientas de Google",
    description: "Curso sobre cómo digitalizar tu negocio utilizando herramientas de Google.",
    logo: "/KnowledgeAssets/Logos/bLogos/google.webp",
    url: "test",
    issuedDate: new Date("2022-10-01"),
    issuedOrganization: "Google",
  },
  {
    title: "Protege tu Negocio: Ciberseguridad en el Teletrabajo",
    description: "Curso sobre ciberseguridad en el teletrabajo.",
    logo: "/KnowledgeAssets/Logos/bLogos/eoi.webp",
    url: "test",
    issuedDate: new Date("2022-10-01"),
    issuedOrganization: "Escuela de Organización Industrial",
  },
  {
    title: "Introduction to Programming Using Python",
    description: "Curso introductorio sobre programación utilizando Python.",
    logo: "/KnowledgeAssets/Logos/bLogos/uurv.webp",
    url: "test",
    issuedDate: new Date("2021-06-01"),
    issuedOrganization: "Universitat Rovira i Virgili",
  },
  {
    title: "Comercio electrónico",
    description: "Curso sobre comercio electrónico.",
    logo: "/KnowledgeAssets/Logos/bLogos/eoi.webp",
    url: "test",
    issuedDate: new Date("2019-08-01"),
    issuedOrganization: "Escuela de Organización Industrial",
  },
  {
    title: "Competencias digitales para profesionales",
    description: "Curso sobre competencias digitales para profesionales.",
    logo: "/KnowledgeAssets/Logos/bLogos/santamar.webp",
    url: "test",
    issuedDate: new Date("2019-08-01"),
    issuedOrganization: "Fundación Santa María la Real del Patrimonio Histórico",
  },
  {
    title: "Transformación digital para el empleo",
    description: "Curso sobre la transformación digital para mejorar la empleabilidad.",
    logo: "/KnowledgeAssets/Logos/bLogos/gentecon.webp",
    url: "test",
    issuedDate: new Date("2019-08-01"),
    issuedOrganization: "Gente con Garantía Juvenil",
  },
  {
    title: "Fundamentos de Marketing Digital",
    description: "Curso sobre los fundamentos del marketing digital.",
    logo: "/KnowledgeAssets/Logos/bLogos/iab.webp",
    url: "test",
    issuedDate: new Date("2019-07-01"),
    issuedOrganization: "IAB",
  },
  {
    title: "Mecanografía",
    description: "Curso sobre mecanografía.",
    logo: "/KnowledgeAssets/Logos/bLogos/unknown.webp",
    url: "test",
    issuedDate: new Date("2018-06-01"),
    issuedOrganization: "Meca Ràpid EMAG1",
  }
];